### ISSUE TITLE
Setup error: Configure build task

### ISSUE THREAD

**Issue by ah3243** [iamhyc/Overleaf-Workshop#125] opened 2024-04-12 18:12 UTC
### Describe the bug
> I've installed and linked it to my overleaf in vs code but when i try and build it, it shows an option in the top input field in vs code saying "no build task to run found. Configure build task..."

Is there any additional setup or configuration needed to get this to build or another extension that i need to include?

### Expected behavior
> that it will build with the files needed for building on the overleaf web client.  

### Environment
 - **Overleaf Workshop Extension version**: [v0.12.0]
 - **VS Code version**: [1.88.1]

**Comment by iamhyc** [comment] 2024-04-13 01:19
> "no build task to run found. Configure build task..."

**Comment by gutbash** [comment] 2024-04-13 03:12
it's not compiling for me. gives me 500 error code or something and the tex has a bunch of errors

**Comment by iamhyc** [comment] 2024-04-13 04:00
> it's not compiling for me. gives me 500 error code or something and the tex has a bunch of errors

@gutbash Can you try with the example project provided by Overleaf and see if it compiles without errors? And if possible, please attach the screenshot of the errors.

**Comment by gutbash** [comment] 2024-04-13 14:39
@iamhyc I'm sorry i think i deleted the overleaf example project. here is the error code when i try to compile though:

```
500: <!DOCTYPE html><html lang="en"><head><title>Something went wrong</title><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="https://cdn.overleaf.com/stylesheets/main-style-82a67b507675f5a9518e.css"></head></html><body class="full-height"><main class="content content-alt full-height" id="main-content"><div class="container full-height"><div class="error-container full-height"><div class="error-details"><p class="error-status">Something went wrong, sorry.</p><p class="error-description">Our staff are probably looking into this, but if it continues, please check our status page at <a href="http://status.overleaf.com">status.overleaf.com</a> or contact us at <a href="mailto:support@overleaf.com">support@overleaf.com</a>.</p><p class="error-actions"><a class="error-btn" href="/">Home</a></p></div></div></div></main></body>
```

the thing is that it works sometimes. when i restart vscode sometimes it works, so i don't think it's an error with my tex. it also compiles fine on overleaf.com. also i am using pdfLaTeX.

**Comment by iamhyc** [comment] 2024-04-13 16:18
> @iamhyc I'm sorry i think i deleted the overleaf example project. here is the error code when i try to compile though:
> 
> the thing is that it works sometimes. when i restart vscode sometimes it works, so i don't think it's an error with my tex. it also compiles fine on overleaf.com. also i am using pdfLaTeX.

@gutbash Hi, I think your problem is related to the network condition and not related to the original problem in this issue.

Please firstly check your network connection following the guidance here: https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md#q3-why-the-extension-loses-connection-to-the-server-frequently-or-loading-indefinitely

If the problem is still there, please help [create a new issue](https://github.com/iamhyc/Overleaf-Workshop/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=).

**Comment by iamhyc** [comment] 2024-04-16 11:15
Since there is no more feedback, I will close this issue now.

If you still have unresolved questions, please create a new issue, or use the discussion section for help.

**Closed by iamhyc** 2024-04-16 11:15 UTC
Labels: question
