### ISSUE TITLE
Cannot Open Local PDF Files After Extension Installation: `The editor could not be opened due to an unexpected error: Invalid uri scheme`

### ISSUE THREAD

**Issue by singularitti** [iamhyc/Overleaf-Workshop#97] opened 2024-02-12 22:53 UTC
Type: <b>Bug</b>

1. **Environment Setup**: Ensure Visual Studio Code is installed with the latest updates. Install the "Overleaf Workshop" extension.
2. **Attempt to Open PDF**: Try to open any local PDF file by navigating to `File > Open File` and selecting a PDF document or by clicking on a PDF file in the Explorer pane within VSCode.
3. **Error Encounter**: Observe the error message that appears in VSCode, preventing the PDF from opening. The error message is as follows:

```
The editor could not be opened due to an unexpected error: Invalid uri scheme: file://*.pdf
```

#### Expected Behavior

Upon attempting to open a PDF file, the expected behavior is for VSCode or another installed extension (such as LaTeX Workshop) that supports PDF rendering to handle the file, allowing it to be viewed either as a rendered document or in its binary format.

#### Actual Behavior

Instead of allowing another extension or VSCode itself to open the PDF file, the installation of "Overleaf Workshop" seems to intercept the process and attempts to open the PDF file, resulting in an error due to an invalid URI scheme. This prevents the file from being opened at all, either as binary or rendered content.

#### Suggested Resolution

It would be beneficial if "Overleaf Workshop" could be updated to exclude handling of local PDF files with the URI scheme `file://*.pdf`, allowing VSCode or other extensions designed for PDF viewing to manage these files. This approach would ensure compatibility and prevent disruptions in workflow for users who regularly work with PDF files within VSCode.

Extension version: 0.9.0
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:57.920Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Memory (System)|32.00GB (3.79GB free)|
|Process Argv||
|VM|0%|
</details>

**Comment by iamhyc** [comment] 2024-02-12 23:54
The problem is that, if we also handle normal PDF files, then "LaTeX Workshop" could not handle the synctex function properly.

Since vscode only allow to activate pdf viewer depending on the filename pattern, users may have multiple extensions registered for the "*.pdf" postfix. There is no fallback or priority mechanism for the extensions.

So for now, I don't have any good idea but only throw the exception to indicate you should not open normal files with our extension. In such case, you can disable our extension temporarily to make other extension works.

**Comment by iamhyc** [comment] 2024-02-13 00:05
ok, I just give it a try and it seems like we can restrict our extension to only open PDF file with scheme `overleaf-workshop`.

Let me fix it now.

**Comment by iamhyc** [comment] 2024-02-13 01:23
> > The problem is that, if we also handle normal PDF files, then "LaTeX Workshop" could not handle the synctex function properly.
> 
> Sorry if I was unclear. I was asking if it is possible to just not open local PDF files (started with `file://`) by this extension? Let other extensions to handle the opening of them.
> 
> > you should not open normal files with our extension
> 
> The problem is, once this extension is installed, I cannot open any local PDF files.
> 
> > I just give it a try and it seems like we can restrict our extension to only open PDF file with scheme overleaf-workshop.
> 
> Great to hear it is fixed, thank you!

Yes, it will be fixed in the next release.

**Closed** 2024-02-13 02:24 UTC
Labels: bug

**Comment by singularitti** [comment] 2024-02-13 04:43
Thank you!

**Comment by e-zz** [comment] 2024-03-11 16:27
Hi, in v0.11.0 this issue recurs. I  have opened another issue #117 about this
