### ISSUE TITLE
[Login Failed] Fail to get User ID

### ISSUE THREAD

**Issue by teamtee** [iamhyc/Overleaf-Workshop#139] opened 2024-05-17 03:21 UTC
### Describe the bug
>I followed the prompts to enter a cookie to log in, but got the Bug alert above

### Expected behavior
> Login

### How To Reproduce
> （1）Get cookie：
from ："oa=1; _gid=GA1.2.2050586700.1715914583; _gat=1; _ga=GA1.1.1269054933.1715914572; _ga_RV4YBCCCWJ=GS1.1.1715914571.1.1.1715915496.0.0.0; overleaf_session2=..."

choose : overleaf_session2=...
>    (2) Login in:
Failed

### Environment
 - **Overleaf Workshop Extension version**: [0.12.1]
 - **VS Code version**: [1.83.0]
 - **Overleaf Edition**: Community

**Comment by iamhyc** [comment] 2024-05-17 03:25
Hi, I delete the cookie leak for you.

Please firstly check your network connection following the guidance here:
https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md#q3-why-the-extension-loses-connection-to-the-server-frequently-or-loading-indefinitely

**Comment by iamhyc** [comment] 2024-05-17 04:43
Hi, I think it is a simple network problem but not a bug.

I will close the issue right now. If you still cannot login, please try to post in the [discussions section](https://github.com/iamhyc/Overleaf-Workshop/discussions).

**Closed by iamhyc** 2024-05-17 04:43 UTC
Labels: question
