### ISSUE TITLE
Duplicated suggestion

### ISSUE THREAD

**Issue by InfluentialSubset** [iamhyc/Overleaf-Workshop#133] opened 2024-05-16 09:14 UTC
### Describe the bug
> A clear and concise description of what the bug is.

Showing duplicated suggestions (sometimes):
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/169728984/9888e44e-0af5-4dfe-8d58-16a540bb3b15)

As above demonstrated, only `algo:look-up-table-adversary` is duplicated, but not `algo:look-up-table-adversary:1`. But overall most of the suggestions are duplicated.

### Expected behavior
> A clear and concise description of what you expected to happen.

Giving a unique suggestion for every entry.

### How To Reproduce
> Detailed steps to reproduce the behavior.

Seems like loading Overleaf-Workshop only already shows this bug, not an interfering issue with other extensions.

### Environment
 - **Overleaf Workshop Extension version**: 0.12.1
 - **VS Code version**: 1.88.1
 - **Overleaf Edition**: Official

**Comment by iamhyc** [comment] 2024-05-16 09:44
Hi, I cannot reproduce the situation at my side. Can you try to make a minimum reproducible example for testing? Thank you!

@QianrenLi If you have time, please also have a look at this one.

**Comment by iamhyc** [comment] 2024-05-16 11:26
It seems like Overleaf would always suggest the reference from other main files. For now, we will follow the behavior and only remove the duplicated suggestions. The fix will be included in the next release.

![image](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/6b3ec980-7334-45c9-bfed-c401be276444)

**Closed** 2024-05-16 11:27 UTC
Labels: bug, confirmed
