### ISSUE TITLE
PDF viewer not working

### ISSUE THREAD

**Issue by Gabriel-TheoChem** [iamhyc/Overleaf-Workshop#199] opened 2024-10-10 21:58 UTC
### Describe the bug
> A clear and concise description of what the bug is.

The PDF viewer in .output section is not running.

### Expected behavior
> A clear and concise description of what you expected to happen.

Preview my file.

This message appears everytime I try to open it:

![image](https://github.com/user-attachments/assets/407534f3-c2e0-484d-92a2-203627451f56)
![overleaf_workshop_bug](https://github.com/user-attachments/assets/7af5398a-250a-4abb-b8b2-beca98c55965)

### How To Reproduce
> Detailed steps to reproduce the behavior.

### Environment
 - **Overleaf Workshop Extension version**: [e.g., 0.7.0]
 - **VS Code version**: [e.g. 1.85.0]
 - **Overleaf Edition**: Official / Community / Enterprise (Server Pro)

### [Optional] Developer Logs
> If applicable, please paste the logs inside the details section below.
> Please find the logs via: Title bar **"Help"** > **"Toggle Developer Tools"** > **"Console"**.

<details>
  ...
</details>

**Comment by iamhyc** [comment] 2024-10-11 01:21
The problem is confirmed. Please wait for a new release with a fix later today.

**Comment by iamhyc** [comment] 2024-10-11 01:40
@Gabriel-TheoChem Please use this auto-generated extension temporarily.
https://github.com/iamhyc/Overleaf-Workshop/actions/runs/11273109014

 I found there is something wrong with my release environment. Will file a new release later.

**Comment by iamhyc** [comment] 2024-10-11 02:19
Please use the latest release `v0.14.1`, the problem should be fixed now. Thanks for you prompt feedback again!

**Closed by iamhyc** 2024-10-11 02:19 UTC
Labels: bug, confirmed

**Comment by TheoAlchemist** [comment] 2024-10-11 16:27
It worked! Thanks a lot!
