### ISSUE TITLE
"Logout from server" doesn't do anything

### ISSUE THREAD

**Issue by Matszwe02** [iamhyc/Overleaf-Workshop#65] opened 2024-01-05 17:36 UTC
### Describe the bug
> A clear and concise description of what the bug is.
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/49353902/a385a005-0861-4b62-8612-bd04ea421b89)
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/49353902/b36e138f-c33f-4909-b7b0-652b21973995)

Cannot logout from server, cannot add a new server, cannot connect to a server, removing cache in "User/.vscode\extensions\iamhyc.overleaf-workshop-0.7.1" doesnt help

### Expected behavior
> A clear and concise description of what you expected to happen.

### How To Reproduce
> Detailed steps to reproduce the behavior.

### Environment
 - **Overleaf Workshop Extension version**: [e.g., 0.7.0]
 - **VS Code version**: [e.g. 1.85.0]
 - **Overleaf Edition**: Official / Community / Enterprise (Server Pro)

### [Optional] Developer Logs
> If applicable, please paste the logs inside the details section below.
> Please find the logs via: Title bar **"Help"** > **"Toggle Developer Tools"** > **"Console"**.

<details>
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'registerIssueDataProvider' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:421  INFO Started local extension host with pid 3988.
log.ts:421  INFO [perf] Render performance baseline is 289ms
webviewElement.ts:513 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:513
log.ts:441   ERR Error: ENOENT: no such file or directory, stat 'c:\Users\matsz\AppData\Roaming\Code\logs\20240105T140816\window3\exthost\output_logging_20240105T182853\4-G-Code.log': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\matsz\AppData\Roaming\Code\logs\20240105T140816\window3\exthost\output_logging_20240105T182853\4-G-Code.log'
    at c.create (C:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:54:3486)
    at w (C:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:54:3600)
    at i.fb (C:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:59:35594)
    at i.stat (C:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:59:28040)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Invalid host defined options
w @ console.ts:137
console.ts:137 [Extension Host] stack trace: TypeError: Invalid host defined options
	at Object.<anonymous> (c:\Users\matsz\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\node_modules\prettier\index.cjs:593:23)
	at o._compile (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\matsz\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\out\intellisense\texDocFormatter.js:5:18)
	at o._compile (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\matsz\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\out\intellisense\langIntellisenseProvider.js:9:27)
	at o._compile (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\matsz\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\out\extension.js:10:36)
	at o._compile (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at f.vb (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:30730)
	at async Promise.all (index 0)
w @ console.ts:137
mainThreadExtensionService.ts:81 [iamhyc.overleaf-workshop]Invalid host defined options
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 TypeError: Invalid host defined options
	at Object.<anonymous> (c:\Users\matsz\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\node_modules\prettier\index.cjs:593:23)
	at o._compile (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\matsz\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\out\intellisense\texDocFormatter.js:5:18)
	at o._compile (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\matsz\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\out\intellisense\langIntellisenseProvider.js:9:27)
	at o._compile (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\matsz\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\out\extension.js:10:36)
	at o._compile (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at f.vb (c:\Users\matsz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:30730)
	at async Promise.all (index 0)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
3notificationsAlerts.ts:42 302: Found. Redirecting to /login?
c @ notificationsAlerts.ts:42
webviewElement.ts:513 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:513
</details>

**Comment by iamhyc** [comment] 2024-01-06 02:33
"Redirect to /login" means your login failed. Please let us know
- what is the server address you used? the default one, or added one?
- what is the login method you used, via email/password, or via cookies?

**Comment by Matszwe02** [comment] 2024-01-06 15:38
Thanks for your short response. I was logged in to a default overleaf.com, with cookies. I'm the one who saw the issue with reconnecting to the network, I haven't logged in or logged out since. I cannot even remove the session to start from scratch. I suggest that you make some option to handle this exception, while still being able to retry logging in.

**Comment by iamhyc** [comment] 2024-01-06 15:44
> Thanks for your short response. I was logged in to a default overleaf.com, with cookies. I'm the one who saw the issue with reconnecting to the network, I haven't logged in or logged out since.

It is not related to "reconnecting". "reconnecting" only happens when you have already opened a project.

> I cannot even remove the session to start from scratch. I suggest that you make some option to handle this exception, while still being able to retry logging in.

There is no session to remove cause you have not logged in. Please make sure you use the correct and valid cookie. You can refer to the [wiki - login with cookies](https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md#login-with-cookies) for help.

**Comment by iamhyc** [comment] 2024-01-06 16:18
Ok, I just got your point why you said "I haven't logged in or logged out since". I saw you in the issue list.

But I just tried to log out and then login, nothing wrong happened. If you have successfully logged in before, please check if your cookie is still valid.

**Comment by Matszwe02** [comment] 2024-01-06 16:28
How to update the cookie? The entire extension is stuck, as I'm seeing, and I can't do anything with it right now.

**Comment by iamhyc** [comment] 2024-01-06 16:42
I wont guess your situation anymore. Do as follows:

- right click on all the servers and remove them
- there will always be a default *unlogged-in* server once you have the list emptied, dont panic
- browse the home page of overleaf in browser, and extract the cookie
- login with the cookie in the extension

if you still fail and want to reset the extension, please seek for information on how to reset vscode globalStorage on internet.

**Comment by iamhyc** [comment] 2024-01-06 17:01
Since your problem apparently has nothing to do with logout and you are exhausted with failed login (302), I will close this issue now.

If you *really* find some thing buggy, create a new issue, fulfiled with the *all necessay* steps to reproduce and *full information*. Thanks you.

**Closed by iamhyc** 2024-01-06 17:01 UTC
Labels: question
